apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world
data:
  APP_NAME: "Laravel"
  APP_ENV: "local"
  APP_DEBUG: "true"
  APP_URL: "http://localhost"

  LOG_CHANNEL: "stderr"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"